/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panola.View;

import java.sql.SQLException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import panola.Controller.StudentTuteDetailsController;
import panola.Controller.TuteController;
import panola.model.Student_Tute_Details;
import panola.model.Tute;
import panola.other.Methods;
import static panola.other.Methods.issueATute;

/**
 *
 * @author Yasiru
 */
public class IssuedTuteDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form IssuedTuteDetails
     */
    public IssuedTuteDetails() {
        initComponents();
    }

    IssuedTuteDetails(String id) throws ClassNotFoundException, SQLException {
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tuteTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TuteIDText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TutenameText = new javax.swing.JTextField();
        IssueButton = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Issued Tute Details");

        tuteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tute Number", "Tute Name", "Issued Date"
            }
        ));
        jScrollPane1.setViewportView(tuteTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tute ID");

        TuteIDText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TuteIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuteIDTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tute Name");

        TutenameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        IssueButton.setText("Issue");
        IssueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TuteIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TutenameText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IssueButton)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TuteIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TutenameText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IssueButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TuteIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuteIDTextActionPerformed
        IssueButton.doClick();
    }//GEN-LAST:event_TuteIDTextActionPerformed

    private void IssueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueButtonActionPerformed
        String tuteID=TuteIDText.getText();
        try {
            String tute = TuteController.getTuteName(tuteID);
            TutenameText.setText(tute);
        } catch (SQLException ex) {
            Logger.getLogger(IssuedTuteDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IssuedTuteDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        String StudentID=MainWindow.idText.getText();
      /*  try {
            
            if(tute!=null){
                TutenameText.setText(tute);
                
                
                Methods.issueATute(tuteID, Date.from(Instant.now()), StudentID);
            }else{
                JOptionPane.showMessageDialog(this, "No Tute Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(IssuedTuteDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IssuedTuteDetails.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        issueATute(tuteID,Date.from(Instant.now()),StudentID);
    }//GEN-LAST:event_IssueButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssueButton;
    private javax.swing.JTextField TuteIDText;
    private javax.swing.JTextField TutenameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tuteTable;
    // End of variables declaration//GEN-END:variables

    public static void viewTable(String id) throws ClassNotFoundException, SQLException {
        ArrayList<Student_Tute_Details> studentTuteDetailsList=StudentTuteDetailsController.getAllDetails(id);
        DefaultTableModel dtm=(DefaultTableModel) tuteTable.getModel();
        dtm.setRowCount(0);
        for (Student_Tute_Details studentTuteDetails : studentTuteDetailsList) {
            Object[] rawData={studentTuteDetails.getTute_ID(),studentTuteDetails.getStudentID(),studentTuteDetails.getDate()};
            dtm.addRow(rawData);
        }
                
    }
}
