/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panola.View;

import static com.alee.laf.combobox.ComboBoxElementType.box;
import static com.alee.managers.style.SupportedComponent.panel;
import com.sun.java.swing.plaf.windows.WindowsBorders;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsDevice;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSLUCENT;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSPARENT;
import static java.awt.GraphicsDevice.WindowTranslucency.TRANSLUCENT;
import java.awt.GraphicsEnvironment;
import java.awt.Paint;
import java.awt.event.MouseEvent;
import java.awt.geom.Ellipse2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.Popup;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.AbstractBorder;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicBorders;
import javax.swing.plaf.metal.MetalBorders;
import javax.swing.plaf.multi.MultiLookAndFeel;
import napkin.DrawnBorder;
import org.ietf.jgss.GSSName;
import org.jdesktop.swingx.JXLabel;
import org.jdesktop.swingx.border.MatteBorderExt;
import org.opencv.core.Core;
import panola.Controller.AttendanceController;
import panola.Controller.PaymentController;
import panola.Controller.StudentBatchSubjectDetailsController;
import panola.Controller.StudentClassFeeController;
import panola.Controller.StudentController;
import panola.Controller.StudentImageController;
import panola.Controller.StudentSubjectBatchDetailsController;
import panola.Controller.SubjectController;
import panola.Controller.TimeTableController;
import panola.Controller.TuteController;
import panola.model.Attendance;
import panola.model.Payment;
import panola.model.Student;
import panola.model.StudentBatchSubjectDetails;
import panola.model.StudentClassFeePayment;
import panola.model.StudentImage;
import panola.model.StudentSubjectBatch;
import panola.model.Subject;
import panola.model.Tute;
import panola.other.ComboSearch;
import panola.other.IDGenarator;
import panola.other.Methods;

/**
 *
 * @author Yasiru
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public MainWindow() {
        initComponents();
        //ImageIcon imageIcon = new ImageIcon("./src/panola/images/insegnare-assistente-italiano-estero-austria-vienna (Custom).png");
        //jXImagePanel1.setImage(imageIcon.getImage());
        setDateAndTime();
        setLocationRelativeTo(null);
        /*Methods.panelTransparance(paymentPanel);
        Methods.panelTransparance(markAttendancePanel);
        Methods.textFieldTransparance(idText);
        Methods.textFieldTransparance(nameText);
        Methods.textFieldTransparance(subjectText);
        Methods.textFieldTransparance(tuteIDText);
        Methods.textFieldTransparance(arrearsText);
        Methods.textFieldTransparance(paidAmountText);
        Methods.textFieldTransparance(balanceText);*/
        markAttendanceButton.setEnabled(false);
      /*  Methods.panelTransparance(Panel);
        Methods.panelTransparance(pane);*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentPopupMenu = new javax.swing.JPopupMenu();
        newStudent = new javax.swing.JMenuItem();
        viewStudent = new javax.swing.JMenuItem();
        subjectPopupMenu = new javax.swing.JPopupMenu();
        newSubject = new javax.swing.JMenuItem();
        updateSubject = new javax.swing.JMenuItem();
        teacherPopupMenu = new javax.swing.JPopupMenu();
        newTecher = new javax.swing.JMenuItem();
        salary = new javax.swing.JMenuItem();
        userPopup = new javax.swing.JPopupMenu();
        signOut = new javax.swing.JMenuItem();
        shutDown = new javax.swing.JMenuItem();
        jXImagePanel1 = new org.jdesktop.swingx.JXImagePanel();
        jLabel2 = new javax.swing.JLabel();
        TimeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        studentLabel = new org.jdesktop.swingx.JXLabel();
        resultLabel = new org.jdesktop.swingx.JXLabel();
        subjectLabel = new org.jdesktop.swingx.JXLabel();
        assingmentLabel = new org.jdesktop.swingx.JXLabel();
        maintainesLabel = new org.jdesktop.swingx.JXLabel();
        teacherLabel = new org.jdesktop.swingx.JXLabel();
        markAttendancePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subjectText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tuteIDText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        markAttendanceButton = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        arrearsText = new javax.swing.JTextField();
        paidAmountText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        paymentHistroyLable = new javax.swing.JLabel();
        pane = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        LogLable = new org.jdesktop.swingx.JXLabel();
        timeTablelable = new org.jdesktop.swingx.JXLabel();

        studentPopupMenu.setBackground(new java.awt.Color(255, 255, 255));
        studentPopupMenu.setAlignmentX(1000.0F);
        studentPopupMenu.setAlignmentY(1000.0F);
        studentPopupMenu.setEnabled(false);

        newStudent.setBackground(new java.awt.Color(255, 255, 255));
        newStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/1417001539_add_48 (Custom).png"))); // NOI18N
        newStudent.setText("New");
        newStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newStudentMouseClicked(evt);
            }
        });
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });
        studentPopupMenu.add(newStudent);

        viewStudent.setBackground(new java.awt.Color(255, 255, 255));
        viewStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/1417001562_search_48 (Custom).png"))); // NOI18N
        viewStudent.setText("View Details");
        viewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentActionPerformed(evt);
            }
        });
        studentPopupMenu.add(viewStudent);

        subjectPopupMenu.setBackground(new java.awt.Color(255, 255, 255));
        subjectPopupMenu.setAlignmentX(-1000.0F);
        subjectPopupMenu.setAlignmentY(-1000.0F);

        newSubject.setBackground(new java.awt.Color(255, 255, 255));
        newSubject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/1417001539_add_48 (Custom).png"))); // NOI18N
        newSubject.setText("New");
        newSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubjectActionPerformed(evt);
            }
        });
        subjectPopupMenu.add(newSubject);

        updateSubject.setBackground(new java.awt.Color(255, 255, 255));
        updateSubject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/2245538_stock-photo-update-icon-orange-button (Custom).jpg"))); // NOI18N
        updateSubject.setText("Update");
        updateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSubjectActionPerformed(evt);
            }
        });
        subjectPopupMenu.add(updateSubject);

        teacherPopupMenu.setBackground(new java.awt.Color(255, 255, 255));

        newTecher.setBackground(new java.awt.Color(255, 255, 255));
        newTecher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newTecher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/1417001539_add_48 (Custom).png"))); // NOI18N
        newTecher.setText("New");
        newTecher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTecherActionPerformed(evt);
            }
        });
        teacherPopupMenu.add(newTecher);

        salary.setBackground(new java.awt.Color(255, 255, 255));
        salary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/Payments_payment_card_credit (Custom).png"))); // NOI18N
        salary.setText("Salary");
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        teacherPopupMenu.add(salary);

        signOut.setBackground(new java.awt.Color(255, 255, 255));
        signOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signOut.setText("SignOut");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });
        userPopup.add(signOut);

        shutDown.setBackground(new java.awt.Color(255, 255, 255));
        shutDown.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        shutDown.setText("Shut Down");
        shutDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutDownActionPerformed(evt);
            }
        });
        userPopup.add(shutDown);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panola Institute of Education");

        jXImagePanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel2.setText("Main Window");

        TimeLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimeLable.setText("08:27:05 AM ");

        dateLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLable.setText("2015/06/16");

        jSeparator1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        studentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel.setText("Student");
        studentLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        studentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        studentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                studentLabelMouseReleased(evt);
            }
        });

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText("Result");
        resultLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        resultLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resultLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resultLabelMouseExited(evt);
            }
        });

        subjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjectLabel.setText("Subject");
        subjectLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        subjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subjectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subjectLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subjectLabelMouseExited(evt);
            }
        });

        assingmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assingmentLabel.setText("Payments");
        assingmentLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        assingmentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        assingmentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assingmentLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assingmentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assingmentLabelMouseExited(evt);
            }
        });

        maintainesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maintainesLabel.setText("Tutes");
        maintainesLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        maintainesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maintainesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintainesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maintainesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maintainesLabelMouseExited(evt);
            }
        });

        teacherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherLabel.setText("Teacher");
        teacherLabel.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        teacherLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        teacherLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacherLabelMousePressed(evt);
            }
        });

        markAttendancePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mark Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 102, 51))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Student ID");

        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student Name");

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject");

        subjectText.setEditable(false);
        subjectText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tute Number");

        tuteIDText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tuteIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuteIDTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Issued Tute Details");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        markAttendanceButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        markAttendanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/mark1 (Custom).jpg"))); // NOI18N
        markAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAttendanceButtonActionPerformed(evt);
            }
        });

        paymentPanel.setBackground(new java.awt.Color(255, 255, 255));
        paymentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 204, 0))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Arrears");

        arrearsText.setEditable(false);
        arrearsText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arrearsText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        arrearsText.setText("0.0");

        paidAmountText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paidAmountText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paidAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidAmountTextActionPerformed(evt);
            }
        });
        paidAmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paidAmountTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidAmountTextKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Paid Amount");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Balance");

        balanceText.setEditable(false);
        balanceText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        paymentHistroyLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paymentHistroyLable.setForeground(java.awt.Color.white);
        paymentHistroyLable.setText("View Payment History");
        paymentHistroyLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentHistroyLableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrearsText, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(paidAmountText, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(balanceText, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(paymentHistroyLable, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrearsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(paidAmountText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(paymentHistroyLable)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout markAttendancePanelLayout = new javax.swing.GroupLayout(markAttendancePanel);
        markAttendancePanel.setLayout(markAttendancePanelLayout);
        markAttendancePanelLayout.setHorizontalGroup(
            markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markAttendancePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(markAttendancePanelLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(markAttendancePanelLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(searchButton))
                        .addGroup(markAttendancePanelLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(subjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(markAttendancePanelLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tuteIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(paymentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markAttendancePanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(markAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(markAttendancePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        markAttendancePanelLayout.setVerticalGroup(
            markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markAttendancePanelLayout.createSequentialGroup()
                .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markAttendancePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameText)
                                .addComponent(searchButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tuteIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(markAttendancePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(markAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Panel.setBackground(new java.awt.Color(93, 124, 217));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/fb.gif"))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        LogLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panola/images/system-shutdown-3 (Custom).png"))); // NOI18N
        LogLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogLableMouseClicked(evt);
            }
        });

        timeTablelable.setText("Time Table");
        timeTablelable.setFont(new java.awt.Font("MV Boli", 0, 22)); // NOI18N
        timeTablelable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeTablelableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeTablelableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeTablelableMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jXImagePanel1Layout = new javax.swing.GroupLayout(jXImagePanel1);
        jXImagePanel1.setLayout(jXImagePanel1Layout);
        jXImagePanel1Layout.setHorizontalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXImagePanel1Layout.createSequentialGroup()
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jXImagePanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXImagePanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(markAttendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(29, 29, 29))
            .addGroup(jXImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jXImagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jXImagePanel1Layout.createSequentialGroup()
                        .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(teacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(timeTablelable, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assingmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(maintainesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jXImagePanel1Layout.setVerticalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogLable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXImagePanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(maintainesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(assingmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timeTablelable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(TimeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jXImagePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markAttendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseEntered
        setBackgroundColourMouseEnter(studentLabel);

    }//GEN-LAST:event_studentLabelMouseEntered

    private void subjectLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectLabelMouseEntered
        setBackgroundColourMouseEnter(subjectLabel);
    }//GEN-LAST:event_subjectLabelMouseEntered

    private void resultLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultLabelMouseEntered
        setBackgroundColourMouseEnter(resultLabel);
    }//GEN-LAST:event_resultLabelMouseEntered

    private void teacherLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseEntered
        setBackgroundColourMouseEnter(teacherLabel);
    }//GEN-LAST:event_teacherLabelMouseEntered

    private void assingmentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assingmentLabelMouseEntered
        setBackgroundColourMouseEnter(assingmentLabel);
    }//GEN-LAST:event_assingmentLabelMouseEntered

    private void studentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseExited
        setBackgroundColourMouseExit(studentLabel);
    }//GEN-LAST:event_studentLabelMouseExited

    private void maintainesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintainesLabelMouseEntered
        setBackgroundColourMouseEnter(maintainesLabel);
    }//GEN-LAST:event_maintainesLabelMouseEntered

    private void subjectLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectLabelMouseExited
        setBackgroundColourMouseExit(subjectLabel);
    }//GEN-LAST:event_subjectLabelMouseExited

    private void resultLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultLabelMouseExited
        setBackgroundColourMouseExit(resultLabel);
    }//GEN-LAST:event_resultLabelMouseExited

    private void teacherLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherLabelMousePressed

    private void teacherLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseExited
        setBackgroundColourMouseExit(teacherLabel);
    }//GEN-LAST:event_teacherLabelMouseExited

    private void assingmentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assingmentLabelMouseExited
        setBackgroundColourMouseExit(assingmentLabel);
    }//GEN-LAST:event_assingmentLabelMouseExited

    private void maintainesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintainesLabelMouseExited
        setBackgroundColourMouseExit(maintainesLabel);
    }//GEN-LAST:event_maintainesLabelMouseExited

    private void studentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseClicked
        evt.translatePoint(-20, 160);
        showPopUp(evt, studentPopupMenu);
    }//GEN-LAST:event_studentLabelMouseClicked

    private void studentLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMousePressed
        formMousePressed(evt, studentPopupMenu);// TODO add your handling code here:
    }//GEN-LAST:event_studentLabelMousePressed

    private void studentLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseReleased
        formMouseReleased(evt, studentPopupMenu);
    }//GEN-LAST:event_studentLabelMouseReleased

    private void newStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newStudentMouseClicked

    }//GEN-LAST:event_newStudentMouseClicked

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        try{
            AddAStudent addAStudent = new AddAStudent();
            addAStudent.setVisible(true);
            this.dispose();
        }catch(NumberFormatException ex){
            AddNewBatch addNewBatch=new AddNewBatch();
            addNewBatch.setVisible(true);
        }
        
    }//GEN-LAST:event_newStudentActionPerformed

    private void subjectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectLabelMouseClicked
        evt.translatePoint(150, 160);
        showPopUp(evt, subjectPopupMenu);
    }//GEN-LAST:event_subjectLabelMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        panola.View.SearchStudentInternal searchStudentInternal = new panola.View.SearchStudentInternal();
        Panel.add(searchStudentInternal);
        searchStudentInternal.setVisible(true);
        Panel.removeAll();
        Panel.add(searchStudentInternal);
        Panel.repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed
        ViewStudentDetails viewStudentDetails = new ViewStudentDetails();
        viewStudentDetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewStudentActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        IssuedTuteDetails issuedTuteDetails;
        try {
            issuedTuteDetails = new IssuedTuteDetails();
            issuedTuteDetails.viewTable(idText.getText());
            Panel.add(issuedTuteDetails);
            // issuedTuteDetails.show();
            issuedTuteDetails.setVisible(true);
            Panel.removeAll();
            Panel.add(issuedTuteDetails);
            Panel.repaint();
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No Tute Issued");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void paymentHistroyLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentHistroyLableMouseClicked
        paymentHistory pHistory = new paymentHistory();
        try {
            pHistory.viewTable(idText.getText());
            Panel.add(pHistory);
            pHistory.setVisible(true);
            Panel.removeAll();
            Panel.add(pHistory);
            Panel.repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_paymentHistroyLableMouseClicked

    private void updateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSubjectActionPerformed
        try{
            UpdateSubjectDetails updateSubjectDetails = new UpdateSubjectDetails();
            updateSubjectDetails.setVisible(true);
            this.dispose();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "No Subject to Update");
        }
    }//GEN-LAST:event_updateSubjectActionPerformed

    private void teacherLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseClicked
        evt.translatePoint(550, 160);
        showPopUp(evt, teacherPopupMenu);
    }//GEN-LAST:event_teacherLabelMouseClicked

    private void newSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubjectActionPerformed
        AddASubject addASubject = new AddASubject();
        addASubject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newSubjectActionPerformed

    private void newTecherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTecherActionPerformed
        AddATeacher addATeacher = new AddATeacher();
        addATeacher.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newTecherActionPerformed

    private void assingmentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assingmentLabelMouseClicked
        Payments payments = new Payments();
        payments.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assingmentLabelMouseClicked

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        TeachersSalary teachersSalary = new TeachersSalary();
        teachersSalary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salaryActionPerformed

    private void maintainesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintainesLabelMouseClicked
        Tutes tutes = new Tutes();
        tutes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_maintainesLabelMouseClicked

    private void resultLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultLabelMouseClicked
        
            Result result = new Result();
            result.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_resultLabelMouseClicked

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed

    }//GEN-LAST:event_nameTextActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        String ID = idText.getText();
        try {
            StudentSubjectBatch studentSubjectBatchDetails = StudentSubjectBatchDetailsController.searchStudent(ID);

            if (studentSubjectBatchDetails != null) {
                subjectText.setText(studentSubjectBatchDetails.getSubject_ID());
                nameText.setText(studentSubjectBatchDetails.getStudentID());
                StudentBatchSubjectDetails studentBatchSubjectDetails = StudentBatchSubjectDetailsController.getNIC(ID);
                if (studentBatchSubjectDetails != null) {
                    StudentImage studentImage = StudentImageController.searchImage(studentBatchSubjectDetails.getLastID());

                    if (studentImage != null) {

                        ImageIcon image = new ImageIcon("C:\\Users\\Yasiru\\Documents\\NetBeansProjects\\Panola\\" + studentBatchSubjectDetails.getLastID() + ".png");
                        JLabel background = new JLabel(image);
                        background.setBounds(0, 0, 300, 250);
                        getLayeredPane().add(background, new Integer(Integer.MIN_VALUE));
                        pane.removeAll();
                        pane.add(background);
                        pane.revalidate();
                        pane.repaint();

                    }
                } else {
                    //JOptionPane.showMessageDialog(this, "NO Such Student");
                }
            }else{
                JOptionPane.showMessageDialog(this, "No Such Student");
            }
            try {
                StudentClassFeePayment studentClassFeePayment = StudentClassFeeController.searchStudentLastPayment(ID);
                if (studentClassFeePayment != null) {
                    int PaidYear = studentClassFeePayment.getPaymentYear();
                    int PaidMouth = studentClassFeePayment.getPaymentMounth();
                    int NowYear = Integer.parseInt(dateLable.getText().substring(0, 4));
                    int NowMounth = Integer.parseInt(dateLable.getText().substring(5, 7));
                    if (PaidYear <= NowYear && PaidMouth <= NowMounth) {
                        double subjectFee = SubjectController.getStudentFee(ID);
                        if (PaidYear == NowYear) {
                            double arrears = subjectFee * (NowMounth - PaidMouth);
                            arrearsText.setText(Double.toString(arrears));
                        } else {
                            double arrears = subjectFee * ((12 + NowMounth) - PaidMouth);
                            arrearsText.setText(Double.toString(arrears));
                        }
                    } else {
                        arrearsText.setText("0.0");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (Double.parseDouble(arrearsText.getText()) == 0.0) {
                markAttendanceButton.setEnabled(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        nameText.setEnabled(false);
        tuteIDText.requestFocus();
        
    }//GEN-LAST:event_idTextActionPerformed

    private void markAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAttendanceButtonActionPerformed

        String ID = idText.getText();
        int Year = Integer.parseInt(idText.getText().substring(0, 4));
        String Category;
        if (idText.getText().substring(4, 5).equals("1")) {
            Category = "Theory";
        } else {
            Category = "Revision";
        }
        String SubjectID = idText.getText().substring(5, 7);
        String RealSubjectID = "Sub_ID0".concat(SubjectID);
        String StudentID = idText.getText().substring(7, 10);
        String Day;
        try {
            Day = TimeTableController.getClassDay(Year, RealSubjectID, Category);
            int year = Integer.parseInt(dateLable.getText().substring(0, 4));
            int month = Integer.parseInt(dateLable.getText().substring(5, 7));
            int day = Integer.parseInt(dateLable.getText().substring(8, 10));

// First convert to Date. This is one of the many ways.
            String dateString = String.format("%d-%d-%d", year, month, day);
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateString);

// Then get the day of week from the Date based on specific locale.
            String dayOfWeek = new SimpleDateFormat("EEEE", Locale.ENGLISH).format(date);
           // System.out.println(dayOfWeek);
            if(dayOfWeek.equals(Day)){
            Attendance attendance = new Attendance(Year, SubjectID, StudentID, dateLable.getText(), TimeLable.getText().substring(9, 10));

            int res = AttendanceController.markAttendance(attendance);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Marked");
                Methods.issueATute(tuteIDText.getText(), Date.from(Instant.now()), idText.getText());
                if (!arrearsText.getText().equals("0.0")) {
                    double classFee = SubjectController.getFee(SubjectController.getSubjectID(subjectText.getText()));
                    double arrears = Double.parseDouble(arrearsText.getText());
                    int mounths = (int) (arrears / classFee);
                    StudentClassFeePayment studentClassFee = StudentClassFeeController.searchStudentLastPayment(ID);
                    int PaidMounth = studentClassFee.getPaymentMounth();
                    for (int i = 0; i < mounths; i++) {
                        String PaymentID = IDGenarator.getNewID("Payment", "PID", "P");

                        Payment payment = new Payment(PaymentID, dateLable.getText(), "Class Fee for '" + (PaidMounth + i) + "'");
                        int res1 = PaymentController.addPayment(payment);
                        if (res1 > 0) {
                            JOptionPane.showMessageDialog(this, "Mounthly Payment Paid");
                            StudentClassFeePayment studentClassFeePayment = new StudentClassFeePayment(ID, PaymentID, classFee, Integer.parseInt(dateLable.getText().substring(0, 4)), Integer.parseInt(dateLable.getText().substring(5, 7)));
                            int res2 = StudentClassFeeController.addNewClassFeePayment(studentClassFeePayment);
                            if (res2 > 0) {
                                JOptionPane.showMessageDialog(this, "Added Class Payment");

                            }
                        }
                    }

                }
            }
            }else{
                JOptionPane.showMessageDialog(this, "Today this student have not class");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        MainWindow mainWindow = new MainWindow();
        mainWindow.setVisible(true);
        idText.setText("");
        this.dispose();  
    }//GEN-LAST:event_markAttendanceButtonActionPerformed

    private void paidAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidAmountTextActionPerformed
        
        double arrearsAmount = Double.parseDouble(arrearsText.getText());
        double paidAmount = Double.parseDouble(paidAmountText.getText());
        double balance = paidAmount - arrearsAmount;
        if (paidAmount >= arrearsAmount) {
            balanceText.setText(String.valueOf(balance));
            markAttendanceButton.setEnabled(true);
        }
         

    }//GEN-LAST:event_paidAmountTextActionPerformed

    private void LogLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogLableMouseClicked
        evt.translatePoint(1200, 45);
        showPopUp(evt, userPopup);
    }//GEN-LAST:event_LogLableMouseClicked

    private void timeTablelableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTablelableMouseEntered
        setBackgroundColourMouseEnter(timeTablelable);
    }//GEN-LAST:event_timeTablelableMouseEntered

    private void timeTablelableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTablelableMouseExited
        setBackgroundColourMouseExit(timeTablelable);
    }//GEN-LAST:event_timeTablelableMouseExited

    private void timeTablelableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTablelableMouseClicked
        TimeTable timeTable=new TimeTable();
        timeTable.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_timeTablelableMouseClicked

    private void idTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyPressed
        if(idText.getText().equals("")){
            nameText.setEnabled(true);
        }else{
            nameText.setEnabled(false);
        }
    }//GEN-LAST:event_idTextKeyPressed

    private void paidAmountTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountTextKeyPressed

        Methods.DigitsOnly(paidAmountText);
    }//GEN-LAST:event_paidAmountTextKeyPressed

    private void tuteIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuteIDTextActionPerformed
      if(paidAmountText.getText().equals("")){
          markAttendanceButton.doClick();
      }
    }//GEN-LAST:event_tuteIDTextActionPerformed

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        UserLogin userLogin=new UserLogin();
        userLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signOutActionPerformed

    private void shutDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutDownActionPerformed
        System.exit(0);
    }//GEN-LAST:event_shutDownActionPerformed

    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased
        String text = idText.getText();
        boolean matches = text.matches("[0-9]{0,15}");
        if (!matches) {
            idText.setText(text.substring(0, text.length() - 1));
        }
    }//GEN-LAST:event_idTextKeyReleased

    private void paidAmountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountTextKeyReleased
        String text = paidAmountText.getText();
        boolean matches = text.matches("[0-9]{0,6}");
        if (!matches) {
            paidAmountText.setText(text.substring(0, text.length() - 1));
        }
    }//GEN-LAST:event_paidAmountTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        // UIManager.setLookAndFeel(new TextureLookAndFeel());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel LogLable;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TimeLable;
    private javax.swing.JTextField arrearsText;
    private org.jdesktop.swingx.JXLabel assingmentLabel;
    private javax.swing.JTextField balanceText;
    public static javax.swing.JLabel dateLable;
    public static final javax.swing.JTextField idText = new javax.swing.JTextField();
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXImagePanel jXImagePanel1;
    private org.jdesktop.swingx.JXLabel maintainesLabel;
    private javax.swing.JButton markAttendanceButton;
    private javax.swing.JPanel markAttendancePanel;
    public static javax.swing.JTextField nameText;
    private javax.swing.JMenuItem newStudent;
    private javax.swing.JMenuItem newSubject;
    private javax.swing.JMenuItem newTecher;
    private javax.swing.JTextField paidAmountText;
    private javax.swing.JPanel pane;
    private javax.swing.JLabel paymentHistroyLable;
    private javax.swing.JPanel paymentPanel;
    private org.jdesktop.swingx.JXLabel resultLabel;
    private javax.swing.JMenuItem salary;
    private javax.swing.JButton searchButton;
    private javax.swing.JMenuItem shutDown;
    private javax.swing.JMenuItem signOut;
    private org.jdesktop.swingx.JXLabel studentLabel;
    private javax.swing.JPopupMenu studentPopupMenu;
    private org.jdesktop.swingx.JXLabel subjectLabel;
    private javax.swing.JPopupMenu subjectPopupMenu;
    private javax.swing.JTextField subjectText;
    private org.jdesktop.swingx.JXLabel teacherLabel;
    private javax.swing.JPopupMenu teacherPopupMenu;
    private org.jdesktop.swingx.JXLabel timeTablelable;
    private javax.swing.JTextField tuteIDText;
    private javax.swing.JMenuItem updateSubject;
    private javax.swing.JPopupMenu userPopup;
    private javax.swing.JMenuItem viewStudent;
    // End of variables declaration//GEN-END:variables

    private void setDateAndTime() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String formetedDate = simpleDateFormat.format(date);
        dateLable.setText(formetedDate);

        Thread t1 = new Thread() {

            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat simpleTimeFormat = new SimpleDateFormat("hh:mm:ss a");
                    String formatedTime = simpleTimeFormat.format(date);
                    TimeLable.setText(formatedTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        };
        t1.start();
    }

    private void setBackgroundColourMouseEnter(JXLabel Label) {
        Label.setBackground(Color.gray);
    }

    private void setBackgroundColourMouseExit(JXLabel Label) {
        Label.setBackgroundPainter(null);
    }

    private void showPopUp(MouseEvent evt, JPopupMenu PopupMenu) {
        PopupMenu.show(this, evt.getX(), evt.getY());
    }

    private void formMousePressed(MouseEvent evt, JPopupMenu PopupMenu) {
        if (evt.isPopupTrigger()) {
            showPopUp(evt, PopupMenu);
        }
    }

    private void formMouseReleased(MouseEvent evt, JPopupMenu PopupMenu) {
        if (evt.isPopupTrigger()) {
            showPopUp(evt, PopupMenu);
        }
    }

}
